# 端口配置
server:
  port: 8080
spring:
  application:
    name: care
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${pictureFile.path-mapping}
  # mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/care?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1234
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.linping.care.controller
# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn
# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
# 图片上传配置
pictureFile:
  path: "/images/"
  path-mapping: "/images/"